const rulesVersion = 'curated-2026-07-17';
const depreciationRulesAnexoUrl = 'https://normas.receita.fazenda.gov.br/sijut2consulta/link.action?idAto=81268';
const depreciationRulesCpc27Url = 'https://s3.sa-east-1.amazonaws.com/static.cpc.aatb.com.br/Documentos/316_CPC_27_rev%2022.pdf';

function fiscalRule(data: {
  id: string;
  ncm: string;
  category: string;
  asset_type: string;
  aliases: string[];
  rate: number;
  life: number;
  official: string;
  terms?: string[];
}) {
  return {
    rule_id: `anexo_iii:${data.id}:${rulesVersion}`,
    document_id: 'in_rfb_1700_2017_anexo_iii',
    version: rulesVersion,
    domain: 'fiscal',
    status: 'vigente',
    category: data.category,
    asset_type: data.asset_type,
    classification_type: data.asset_type,
    ncm: data.ncm,
    aliases: data.aliases,
    match_terms: data.terms || data.aliases,
    depreciation_rate: data.rate,
    useful_life_years: data.life,
    unit_rate: 'percent_per_year',
    unit_life: 'years',
    source_section: `Anexo III - Posicao ${data.ncm}`,
    official_description: data.official,
    source_url: depreciationRulesAnexoUrl,
    raw_reference: `Anexo III da IN RFB 1.700/2017; posicao ${data.ncm}; prazo ${data.life} anos; taxa ${data.rate}% ao ano.`,
    notes: 'Regra fiscal estruturada local em subconjunto curado; exige confirmacao fiscal para aplicacao.',
  };
}

export const DEPRECIATION_RULES_DATA = [
  fiscalRule({
    id: 'instalacoes',
    ncm: 'instalacoes',
    category: 'Equipamentos',
    asset_type: 'installation',
    aliases: ['instalacoes', 'instalacao eletrica', 'instalacao hidraulica', 'instalacao industrial'],
    rate: 10,
    life: 10,
    official: 'Instalacoes.',
  }),
  fiscalRule({
    id: 'edificacoes',
    ncm: 'edificacoes',
    category: 'Imoveis',
    asset_type: 'property',
    aliases: ['edificacoes', 'predio', 'galpao', 'edificio', 'construcao', 'benfeitoria'],
    rate: 4,
    life: 25,
    official: 'Edificacoes.',
  }),
  fiscalRule({
    id: 'tratores_8701',
    ncm: '8701',
    category: 'Veiculos',
    asset_type: 'agricultural_machine',
    aliases: ['trator', 'trator agricola', 'trator rodoviario'],
    rate: 25,
    life: 4,
    official: 'Tratores, exceto os carros-tratores da posicao 8709.',
  }),
  fiscalRule({
    id: 'onibus_8702',
    ncm: '8702',
    category: 'Veiculos',
    asset_type: 'vehicle',
    aliases: ['onibus', 'micro onibus', 'van transporte passageiros'],
    rate: 25,
    life: 4,
    official: 'Veiculos automoveis para transporte de dez pessoas ou mais, incluindo o motorista.',
  }),
  fiscalRule({
    id: 'veiculos_8703',
    ncm: '8703',
    category: 'Veiculos',
    asset_type: 'vehicle',
    aliases: ['automovel', 'carro', 'veiculo de passageiros', 'camioneta', 'utilitario'],
    rate: 20,
    life: 5,
    official: 'Automoveis de passageiros e outros veiculos automoveis principalmente concebidos para transporte de pessoas.',
  }),
  fiscalRule({
    id: 'caminhoes_8704',
    ncm: '8704',
    category: 'Veiculos',
    asset_type: 'vehicle',
    aliases: ['caminhao', 'veiculo de carga', 'furgon', 'caminhonete de carga'],
    rate: 25,
    life: 4,
    official: 'Veiculos automoveis para transporte de mercadorias.',
  }),
  fiscalRule({
    id: 'motocicletas_8711',
    ncm: '8711',
    category: 'Veiculos',
    asset_type: 'vehicle',
    aliases: ['motocicleta', 'moto', 'ciclomotor'],
    rate: 25,
    life: 4,
    official: 'Motocicletas, incluindo ciclomotores, e ciclos equipados com motor auxiliar.',
  }),
  fiscalRule({
    id: 'computadores_8471',
    ncm: '8471',
    category: 'Equipamentos',
    asset_type: 'computer_equipment',
    aliases: ['maquinas automaticas para processamento de dados', 'computador', 'notebook', 'laptop', 'desktop', 'servidor fisico', 'workstation', 'equipamento de informatica'],
    rate: 20,
    life: 5,
    official: 'Maquinas automaticas para processamento de dados e suas unidades.',
  }),
  fiscalRule({
    id: 'impressoras_scanners_8443',
    ncm: '8443',
    category: 'Equipamentos',
    asset_type: 'computer_equipment',
    aliases: ['impressora', 'scanner', 'multifuncional', 'aparelho de impressao'],
    rate: 10,
    life: 10,
    official: 'Maquinas e aparelhos de impressao, copiadoras e telecopiadores; partes e acessorios.',
  }),
  fiscalRule({
    id: 'moveis_9403',
    ncm: '9403',
    category: 'Equipamentos',
    asset_type: 'furniture',
    aliases: ['moveis de escritorio', 'mesa', 'cadeira', 'armario', 'arquivo', 'estante', 'mobiliario'],
    rate: 10,
    life: 10,
    official: 'Outros moveis e suas partes.',
  }),
  fiscalRule({
    id: 'mobiliario_medico_9402',
    ncm: '9402',
    category: 'Equipamentos',
    asset_type: 'medical_equipment',
    aliases: ['mobiliario medico', 'mesa de operacao', 'mesa de exame', 'cama hospitalar', 'cadeira de dentista'],
    rate: 10,
    life: 10,
    official: 'Mobiliario para medicina, cirurgia, odontologia ou veterinaria.',
  }),
  fiscalRule({
    id: 'instrumentos_medicos_9018',
    ncm: '9018',
    category: 'Equipamentos',
    asset_type: 'medical_equipment',
    aliases: ['instrumentos de medicina', 'cirurgia', 'odontologia', 'veterinaria', 'monitor multiparametrico', 'bomba de infusao', 'desfibrilador'],
    rate: 10,
    life: 10,
    official: 'Instrumentos e aparelhos para medicina, cirurgia, odontologia ou veterinaria.',
  }),
  fiscalRule({
    id: 'raio_x_9022',
    ncm: '9022',
    category: 'Equipamentos',
    asset_type: 'medical_equipment',
    aliases: ['raio x', 'radiologia', 'tomografia', 'aparelho radiografico'],
    rate: 10,
    life: 10,
    official: 'Aparelhos de raios X e aparelhos que utilizem radiacoes alfa, beta ou gama.',
  }),
  fiscalRule({
    id: 'geradores_8502',
    ncm: '8502',
    category: 'Equipamentos',
    asset_type: 'generator',
    aliases: ['grupo eletrogeno', 'gerador de energia', 'gerador diesel', 'gerador kva'],
    rate: 10,
    life: 10,
    official: 'Grupos eletrogenos e conversores rotativos eletricos.',
  }),
  fiscalRule({
    id: 'motores_8501',
    ncm: '8501',
    category: 'Equipamentos',
    asset_type: 'industrial_machine',
    aliases: ['motor eletrico', 'gerador eletrico', 'maquina eletrica'],
    rate: 10,
    life: 10,
    official: 'Motores e geradores eletricos, exceto grupos eletrogenos.',
  }),
  fiscalRule({
    id: 'bombas_8413',
    ncm: '8413',
    category: 'Equipamentos',
    asset_type: 'industrial_machine',
    aliases: ['bomba centrifuga', 'bomba hidraulica', 'bomba para liquidos'],
    rate: 10,
    life: 10,
    official: 'Bombas para liquidos, mesmo com dispositivo medidor; elevadores de liquidos.',
  }),
  fiscalRule({
    id: 'compressores_8414',
    ncm: '8414',
    category: 'Equipamentos',
    asset_type: 'industrial_machine',
    aliases: ['compressor', 'bomba de ar', 'ventilador industrial', 'exaustor'],
    rate: 10,
    life: 10,
    official: 'Bombas de ar ou de vacuo, compressores de ar ou de outros gases e ventiladores.',
  }),
  fiscalRule({
    id: 'refrigeracao_8418',
    ncm: '8418',
    category: 'Equipamentos',
    asset_type: 'installation',
    aliases: ['refrigerador', 'freezer', 'camara fria', 'equipamento de refrigeracao'],
    rate: 10,
    life: 10,
    official: 'Refrigeradores, congeladores e outros materiais, maquinas e aparelhos para producao de frio.',
  }),
  fiscalRule({
    id: 'maquinas_agricolas_8432',
    ncm: '8432',
    category: 'Equipamentos',
    asset_type: 'agricultural_machine',
    aliases: ['maquina agricola', 'plantadeira', 'semeadora', 'arado', 'grade agricola'],
    rate: 10,
    life: 10,
    official: 'Maquinas, aparelhos e equipamentos agricolas, horticolas ou florestais para preparacao ou trabalho do solo ou para cultura.',
    terms: ['plantadeira', 'semeadora', 'arado', 'grade agricola', 'preparacao do solo'],
  }),
  fiscalRule({
    id: 'maquinas_agricolas_8433',
    ncm: '8433',
    category: 'Equipamentos',
    asset_type: 'agricultural_machine',
    aliases: ['colheitadeira', 'debulhadora', 'ceifeira', 'maquina para colheita'],
    rate: 10,
    life: 10,
    official: 'Maquinas e aparelhos para colheita ou debulha, incluindo enfardadeiras e ceifeiras.',
    terms: ['colheitadeira', 'colheita', 'debulha', 'ceifeira'],
  }),
  ...['8456', '8457', '8458', '8459', '8460', '8461', '8462', '8463', '8464', '8465', '8466'].map((ncm) => fiscalRule({
    id: `maquinas_ferramenta_${ncm}`,
    ncm,
    category: 'Equipamentos',
    asset_type: 'industrial_machine',
    aliases: ['maquina ferramenta', 'torno', 'fresadora', 'prensa', 'centro de usinagem'],
    rate: 10,
    life: 10,
    official: `Maquinas-ferramenta e aparelhos da posicao ${ncm}, conforme classificacao fiscal aplicavel.`,
    terms: ['maquina ferramenta', 'usinagem', 'torno', 'fresadora', 'prensa'],
  })),
  ...['9026', '9027', '9028', '9029', '9030', '9031', '9032'].map((ncm) => fiscalRule({
    id: `instrumentos_medida_${ncm}`,
    ncm,
    category: 'Equipamentos',
    asset_type: 'industrial_machine',
    aliases: ['instrumento de medida', 'osciloscopio', 'multimetro', 'controlador automatico', 'contador', 'tacometro'],
    rate: 10,
    life: 10,
    official: `Instrumentos e aparelhos da posicao ${ncm}, conforme classificacao fiscal aplicavel.`,
    terms: ['medicao', 'controle', 'instrumento', 'controlador', 'contador'],
  })),
  {
    rule_id: `accounting:cpc_27_general:${rulesVersion}`,
    document_id: 'cpc_27',
    version: rulesVersion,
    domain: 'accounting',
    status: 'vigente',
    aliases: ['ativo imobilizado', 'depreciacao', 'vida util', 'valor residual', 'maquinas', 'equipamentos', 'veiculos', 'moveis'],
    match_terms: ['ativo imobilizado', 'vida util', 'valor residual', 'depreciacao'],
    residual_guidance: 'Estimar valor residual considerando valor esperado de alienacao liquido de despesas, condicao final esperada, uso, manutencao e mercado observavel quando houver.',
    source_section: 'CPC 27 itens 50 a 62',
    official_description: 'Orientacao contabil geral sobre depreciacao, vida util, valor residual e metodo.',
    source_url: depreciationRulesCpc27Url,
    raw_reference: 'CPC 27, itens 50 a 62; nao fornece taxa fixa universal.',
    notes: 'Orientacao contabil geral; nao fornece taxa fixa universal.',
  },
  {
    rule_id: `accounting:cpc_27_land:${rulesVersion}`,
    document_id: 'cpc_27',
    version: rulesVersion,
    domain: 'accounting',
    status: 'vigente',
    category: 'Imoveis',
    asset_type: 'property',
    aliases: ['terreno', 'terra nua', 'lote'],
    match_terms: ['terreno', 'terra nua', 'lote'],
    residual_guidance: 'Terreno normalmente nao e depreciado; separar de edificacoes e melhoramentos.',
    source_section: 'CPC 27 item 58',
    official_description: 'Terrenos e edificios devem ser contabilizados separadamente; terrenos normalmente nao sao depreciados.',
    source_url: depreciationRulesCpc27Url,
    raw_reference: 'CPC 27, item 58; terreno geralmente possui vida util ilimitada e nao e depreciado.',
    notes: 'Usar para bloquear depreciacao automatica de terreno isolado.',
  },
  {
    rule_id: `accounting:cpc_04_intangible:${rulesVersion}`,
    document_id: 'cpc_04',
    version: rulesVersion,
    domain: 'accounting',
    status: 'vigente',
    category: 'Intangiveis',
    asset_type: 'intangible_asset',
    aliases: ['software', 'licenca', 'patente', 'marca', 'direito de uso'],
    match_terms: ['software', 'licenca', 'intangivel', 'amortizacao'],
    residual_guidance: 'Avaliar vida util definida ou indefinida e amortizacao; nao tratar como depreciacao de imobilizado.',
    source_section: 'CPC 04',
    official_description: 'Orientacao para ativos intangiveis e vida util definida ou indefinida.',
    source_url: 'https://www.cpc.org.br/CPC/Documentos-Emitidos/Pronunciamentos',
    raw_reference: 'CPC 04; ativo intangivel deve ser avaliado conforme vida util e amortizacao aplicavel.',
    notes: 'Orientacao para intangiveis.',
  },
  {
    rule_id: 'historical:maquinas_equipamentos_revogada',
    document_id: 'in_rfb_1700_2017_anexo_iii',
    version: 'historical-revogado-seed',
    domain: 'fiscal',
    status: 'revogado',
    category: 'Equipamentos',
    asset_type: 'industrial_machine',
    classification_type: 'industrial_machine',
    aliases: ['maquina', 'equipamento', 'gerador', 'compressor', 'prensa', 'motor'],
    match_terms: ['maquina', 'equipamento'],
    depreciation_rate: 99,
    useful_life_years: 1,
    unit_rate: 'percent_per_year',
    unit_life: 'years',
    source_section: 'Anexo III historico',
    official_description: 'Regra historica revogada apenas para testes de exclusao.',
    source_url: depreciationRulesAnexoUrl,
    raw_reference: 'Regra historica revogada; nao deve fundamentar sugestoes.',
    notes: 'Regra historica revogada usada apenas para validar que versoes revogadas nao fundamentam sugestoes.',
  },
] as const;
