const aliasesVersion = 'curated-2026-07-17';

export const CLASSIFICATION_ALIASES_DATA = [
  { alias_id: `alias:gerador:${aliasesVersion}`, normalized: 'gerador', category: 'Equipamentos', asset_type: 'generator', ncm: '8502', rule_ids: [`anexo_iii:geradores_8502:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'exact', priority: 95, context_terms: ['kva', 'diesel', 'energia', 'grupo eletrogeno'], excluded_terms: [], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:notebook:${aliasesVersion}`, normalized: 'notebook', category: 'Equipamentos', asset_type: 'computer_equipment', ncm: '8471', rule_ids: [`anexo_iii:computadores_8471:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'exact', priority: 95, context_terms: ['computador', 'informatica', 'processamento de dados'], excluded_terms: [], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:macbook:${aliasesVersion}`, normalized: 'macbook', category: 'Equipamentos', asset_type: 'computer_equipment', ncm: '8471', rule_ids: [`anexo_iii:computadores_8471:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'partial', priority: 60, context_terms: ['notebook', 'computador', 'processamento de dados'], excluded_terms: [], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:servidor_fisico:${aliasesVersion}`, normalized: 'servidor fisico', category: 'Equipamentos', asset_type: 'computer_equipment', ncm: '8471', rule_ids: [`anexo_iii:computadores_8471:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'exact', priority: 90, context_terms: ['rack', 'storage', 'datacenter'], excluded_terms: ['servidor em nuvem', 'cloud', 'saas'], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:monitor_computador:${aliasesVersion}`, normalized: 'monitor', category: 'Equipamentos', asset_type: 'computer_equipment', rule_ids: [`accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['cpc_27'], match_type: 'partial', priority: 35, context_terms: ['computador', 'video', 'display', 'informatica'], excluded_terms: ['multiparametrico', 'hospitalar', 'paciente', 'monitor de paciente'], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:impressora:${aliasesVersion}`, normalized: 'impressora', category: 'Equipamentos', asset_type: 'computer_equipment', ncm: '8443', rule_ids: [`anexo_iii:impressoras_scanners_8443:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'exact', priority: 85, context_terms: ['multifuncional', 'scanner'], excluded_terms: [], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:veiculo:${aliasesVersion}`, normalized: 'veiculo', category: 'Veiculos', asset_type: 'vehicle', ncm: '8703', rule_ids: [`anexo_iii:veiculos_8703:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'partial', priority: 70, context_terms: ['automovel', 'carro', 'utilitario'], excluded_terms: [], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:caminhao:${aliasesVersion}`, normalized: 'caminhao', category: 'Veiculos', asset_type: 'vehicle', ncm: '8704', rule_ids: [`anexo_iii:caminhoes_8704:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'exact', priority: 95, context_terms: ['carga', 'diesel'], excluded_terms: [], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:onibus:${aliasesVersion}`, normalized: 'onibus', category: 'Veiculos', asset_type: 'vehicle', ncm: '8702', rule_ids: [`anexo_iii:onibus_8702:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'exact', priority: 95, context_terms: ['transporte passageiros', 'micro onibus'], excluded_terms: [], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:trator:${aliasesVersion}`, normalized: 'trator', category: 'Veiculos', asset_type: 'agricultural_machine', ncm: '8701', rule_ids: [`anexo_iii:tratores_8701:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'exact', priority: 100, context_terms: ['agricola', 'rodoviario', 'diesel'], excluded_terms: [], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:motocicleta:${aliasesVersion}`, normalized: 'motocicleta', category: 'Veiculos', asset_type: 'vehicle', ncm: '8711', rule_ids: [`anexo_iii:motocicletas_8711:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'exact', priority: 95, context_terms: ['moto', 'ciclomotor'], excluded_terms: [], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:monitor_multiparametrico:${aliasesVersion}`, normalized: 'monitor multiparametrico', category: 'Equipamentos', asset_type: 'medical_equipment', ncm: '9018', rule_ids: [`anexo_iii:instrumentos_medicos_9018:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'exact', priority: 100, context_terms: ['paciente', 'hospitalar', 'medico'], excluded_terms: ['monitor de computador'], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:bomba_infusao:${aliasesVersion}`, normalized: 'bomba de infusao', category: 'Equipamentos', asset_type: 'medical_equipment', ncm: '9018', rule_ids: [`anexo_iii:instrumentos_medicos_9018:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'exact', priority: 100, context_terms: ['hospitalar', 'medico'], excluded_terms: ['bomba hidraulica'], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:raio_x:${aliasesVersion}`, normalized: 'raio x', category: 'Equipamentos', asset_type: 'medical_equipment', ncm: '9022', rule_ids: [`anexo_iii:raio_x_9022:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'exact', priority: 100, context_terms: ['radiologia', 'tomografia'], excluded_terms: [], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:mesa_cadeira:${aliasesVersion}`, normalized: 'mesa cadeira armario mobiliario', category: 'Equipamentos', asset_type: 'furniture', ncm: '9403', rule_ids: [`anexo_iii:moveis_9403:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'partial', priority: 80, context_terms: ['escritorio', 'moveis', 'utensilios'], excluded_terms: ['mesa cirurgica', 'mesa de operacao'], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:mesa_hospitalar:${aliasesVersion}`, normalized: 'mesa de operacao cama hospitalar cadeira de dentista', category: 'Equipamentos', asset_type: 'medical_equipment', ncm: '9402', rule_ids: [`anexo_iii:mobiliario_medico_9402:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'partial', priority: 90, context_terms: ['hospitalar', 'medico', 'cirurgica'], excluded_terms: [], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:terreno:${aliasesVersion}`, normalized: 'terreno', category: 'Imóveis', asset_type: 'property', rule_ids: [`accounting:cpc_27_land:${aliasesVersion}`], document_ids: ['cpc_27', 'in_rfb_1700_2017'], match_type: 'exact', priority: 100, context_terms: ['terra nua', 'lote'], excluded_terms: ['edificacao', 'construcao', 'benfeitoria'], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:edificacao:${aliasesVersion}`, normalized: 'edificacao predio galpao construcao benfeitoria', category: 'Imóveis', asset_type: 'property', ncm: undefined, rule_ids: [`anexo_iii:edificacoes:${aliasesVersion}`, `accounting:cpc_27_general:${aliasesVersion}`], document_ids: ['in_rfb_1700_2017_anexo_iii', 'cpc_27'], match_type: 'partial', priority: 90, context_terms: ['imovel', 'construcao', 'galpao'], excluded_terms: ['terreno isolado'], origin: 'seed_curated', status: 'vigente' },
  { alias_id: `alias:software:${aliasesVersion}`, normalized: 'software licenca erp sistema', category: 'Intangíveis', asset_type: 'intangible_asset', rule_ids: [`accounting:cpc_04_intangible:${aliasesVersion}`], document_ids: ['cpc_04'], match_type: 'partial', priority: 90, context_terms: ['licenca', 'erp', 'direito de uso'], excluded_terms: ['hardware'], origin: 'seed_curated', status: 'vigente' },
] as const;
