const documentsCheckedAt = '2026-07-17T00:00:00-03:00';
const documentsVersion = 'curated-2026-07-17';

export const NORMATIVE_DOCUMENTS_DATA = [
  { document_id: 'cpc_27', source_id: 'cpc', title: 'CPC 27 - Ativo Imobilizado', authority: 'CPC', document_type: 'Pronunciamento Tecnico', number: '27', domain: 'accounting', status: 'vigente', effective_start: '2009-07-31', official_url: 'https://s3.sa-east-1.amazonaws.com/static.cpc.aatb.com.br/Documentos/316_CPC_27_rev%2022.pdf', version: documentsVersion, content_hash: 'curated-cpc-27-rev-22-2026-07-17', last_checked_at: documentsCheckedAt, normalized_text: 'Conteudo curado com itens sobre valor depreciavel, vida util, valor residual, terrenos, metodos e revisao anual.' },
  { document_id: 'cpc_23', source_id: 'cpc', title: 'CPC 23 - Politicas Contabeis, Mudanca de Estimativa e Retificacao de Erro', authority: 'CPC', document_type: 'Pronunciamento Tecnico', number: '23', domain: 'accounting', status: 'vigente', official_url: 'https://www.cpc.org.br/CPC/Documentos-Emitidos/Pronunciamentos', version: documentsVersion, content_hash: 'curated-cpc-23-2026-07-17', last_checked_at: documentsCheckedAt, normalized_text: 'Conteudo curado sobre mudanca de estimativa contabil prospectiva.' },
  { document_id: 'cpc_04', source_id: 'cpc', title: 'CPC 04 - Ativo Intangivel', authority: 'CPC', document_type: 'Pronunciamento Tecnico', number: '04', domain: 'accounting', status: 'vigente', official_url: 'https://www.cpc.org.br/CPC/Documentos-Emitidos/Pronunciamentos', version: documentsVersion, content_hash: 'curated-cpc-04-2026-07-17', last_checked_at: documentsCheckedAt, normalized_text: 'Conteudo curado com vida util definida e indefinida de ativo intangivel.' },
  { document_id: 'cpc_01', source_id: 'cpc', title: 'CPC 01 - Reducao ao Valor Recuperavel de Ativos', authority: 'CPC', document_type: 'Pronunciamento Tecnico', number: '01', domain: 'accounting', status: 'vigente', official_url: 'https://www.cpc.org.br/CPC/Documentos-Emitidos/Pronunciamentos', version: documentsVersion, content_hash: 'curated-cpc-01-2026-07-17', last_checked_at: documentsCheckedAt, normalized_text: 'Conteudo curado para impairment e valor recuperavel, sem substituir taxa ou vida util.' },
  { document_id: 'cpc_28', source_id: 'cpc', title: 'CPC 28 - Propriedade para Investimento', authority: 'CPC', document_type: 'Pronunciamento Tecnico', number: '28', domain: 'accounting', status: 'vigente', official_url: 'https://www.cpc.org.br/CPC/Documentos-Emitidos/Pronunciamentos', version: documentsVersion, content_hash: 'curated-cpc-28-2026-07-17', last_checked_at: documentsCheckedAt, normalized_text: 'Conteudo curado para separar propriedade para investimento de ativo imobilizado de uso proprio.' },
  { document_id: 'icpc_10', source_id: 'cpc', title: 'ICPC 10 / ITG 10 - Interpretacao sobre Ativo Imobilizado', authority: 'CPC/CFC', document_type: 'Interpretacao', number: '10', domain: 'accounting', status: 'vigente', official_url: 'https://www.cpc.org.br/CPC/Documentos-Emitidos/Interpretacoes', version: documentsVersion, content_hash: 'curated-icpc-itg-10-2026-07-17', last_checked_at: documentsCheckedAt, normalized_text: 'Conteudo curado sobre revisao inicial de vida util e valor residual em ativo imobilizado.' },
  { document_id: 'in_rfb_1700_2017', source_id: 'receita_sijut2', title: 'IN RFB 1.700/2017 - artigos de depreciacao', authority: 'Receita Federal', document_type: 'Instrucao Normativa', number: '1700', year: 2017, domain: 'fiscal', status: 'vigente', official_url: 'https://www.in.gov.br/web/dou/-/instrucao-normativa-n-1-700-de-14-de-marco-de-2017-20479996', version: documentsVersion, content_hash: 'curated-in-rfb-1700-artigos-120-125-2026-07-17', last_checked_at: documentsCheckedAt, normalized_text: 'Artigos 120 a 125 curados da publicacao oficial DOU para capitalizacao e depreciacao fiscal.' },
  { document_id: 'in_rfb_1700_2017_anexo_iii', source_id: 'receita_sijut2', title: 'IN RFB 1.700/2017 - Anexo III', authority: 'Receita Federal', document_type: 'Instrucao Normativa - Anexo', number: '1700', year: 2017, domain: 'fiscal', status: 'vigente', official_url: 'https://normas.receita.fazenda.gov.br/sijut2consulta/link.action?idAto=81268', version: documentsVersion, content_hash: 'curated-anexo-iii-parcial-2026-07-17', last_checked_at: documentsCheckedAt, normalized_text: 'Tabela fiscal estruturada localmente em subconjunto curado. Nao declarada integral sem reconciliacao oficial linha a linha.' },
  { document_id: 'decreto_9580_2018', source_id: 'planalto', title: 'Decreto 9.580/2018 - Regulamento do Imposto sobre a Renda', authority: 'Planalto', document_type: 'Decreto', number: '9580', year: 2018, domain: 'fiscal', status: 'vigente', official_url: 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/decreto/d9580.htm', version: documentsVersion, content_hash: 'curated-rir-2018-2026-07-17', last_checked_at: documentsCheckedAt, normalized_text: 'Base curada do RIR/2018 como suporte legal fiscal complementar.' },
  { document_id: 'lei_14871_2024', source_id: 'planalto', title: 'Lei 14.871/2024 - Depreciacao Acelerada', authority: 'Planalto', document_type: 'Lei', number: '14871', year: 2024, domain: 'fiscal', status: 'vigente', official_url: 'https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/l14871.htm', version: documentsVersion, content_hash: 'curated-lei-14871-2026-07-17', last_checked_at: documentsCheckedAt, normalized_text: 'Depreciacao acelerada sujeita a elegibilidade; nao fundamenta depreciacao fiscal comum neste contrato.' },
  { document_id: 'ncm_tabela', source_id: 'siscomex_ncm', title: 'NCM - Nomenclatura Comum do Mercosul', authority: 'Receita Federal/Siscomex', document_type: 'Tabela de Classificacao', domain: 'classification', status: 'vigente', official_url: 'https://www.gov.br/receitafederal/pt-br/assuntos/aduana-e-comercio-exterior/classificacao-fiscal-de-mercadorias/ncm', version: documentsVersion, content_hash: 'curated-ncm-2026-07-17', last_checked_at: documentsCheckedAt, normalized_text: 'Referencia para descricoes e codigos NCM relacionados ao Anexo III.' },
] as const;
